image:
- Visual Studio 2015
- Visual Studio 2017
- Ubuntu
version: '{build}'
configuration:
  - Debug
  - Release
build_script:
  - echo "Building for %CONFIGURATION%"
  - dotnet build src/ReportGenerator.Console.NetCore/ReportGenerator.Console.NetCore.csproj /p:Configuration=%CONFIGURATION%
test_script:
  - cd src
  - cmd: .\build.bat
  - sh: msbuild Testprojects/CSharp/Project/Test_CSharp.csproj /t:Restore /v:m
  - sh: msbuild build.proj /t:Restore /v:m
  - sh: msbuild build.proj /v:m
  - sh: dotnet test ReportGenerator.Core.Test/ReportGenerator.Core.Test.csproj